services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # Remove these to avoid enabling auth via init user
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: app
    #   MONGO_INITDB_ROOT_PASSWORD: app_pw
    #   MONGO_INITDB_DATABASE: suspicious
    networks:
      - pre-exam
  
  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    networks:
      - pre-exam



  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    ports:
      - "9092:9092" # TODO: change if port 9092 is already used
    environment:
      CLUSTER_ID: "Mf_-9PUJQnCI6eQZzgFTlg" # TODO: set per project
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      # listeners
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092" # TODO: if you change host port 9092, update this
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # single node dev defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - pre-exam


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "18080:8080" # TODO: change if port 8080 is already used
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      - kafka
    networks:
      - pre-exam

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - pre-exam

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - pre-exam

  # ingestion-service:
  #   build:
  #     context: .
  #     dockerfile: ingestion_service/Dockerfile
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  #     MONGO_HOST: mongo
  #     TESSERACT_CMD: /usr/bin/tesseract
  #     IMAGES_PATH: /data/tweet_images
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data/messaging_images/tweet_images:/data/tweet_images:ro
  #   depends_on:
  #     - kafka
  #     - mongo
  #   networks:
  #     - es

  metadata_service:
    build:
      context: .   # makes the docker file copy the whole project
      dockerfile: metadata_service/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./podcasts:/app/podcasts
    depends_on:
      - kafka
    networks:
      - pre-exam

  db_inserter:
    build:
      context: .
      dockerfile: db_inserter/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./podcasts:/app/podcasts
    depends_on:
      - kafka
      - elasticsearch
      - mongo
    networks:
      - pre-exam

  ttl_service:
    build:
      context: .
      dockerfile: TTL_service/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./podcasts:/app/podcasts
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - pre-exam

  # streamlit_ui:
  #   build:
  #     context: .
  #     dockerfile: streamlit_app/Dockerfile
  #   environment:
  #     ELASTICSEARCH_HOST: http://elasticsearch
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - es


volumes:
  esdata:
  mongo_data:

networks:
  pre-exam:
    driver: bridge
